package requests;

public enum RequestType {
    REGISTER,
    LOGIN,
    LOGOUT,
    USERLIST,
    WHISPER,
    CHAT,
    CREATE,
    JOIN,
    LOBBYLIST,
    CHANGE_CREDENTIAL,
    CHANGE_COLOR,
    SET_READY,
    START_GAME,
    LEAVE_LOBBY,
    RESUPPLY_STORAGE,
    LEAD_TOOL_CARD,
    LOAD_UP_SHIP,
    VOYAGE_TO_STONE_SITE,
    VOYAGE_TO_STONE_SITE_MANUAL_DUMP,
    VOYAGE_TO_MARKET,
    CHOOSE_CARD
}
